name: GalacticfyChat
version: 0.0
main: de.galacticfy.galacticfyChat.GalacticfyChat
api-version: '1.21'
softdepend:
  - LibsDisguises

commands:
  npc:
    description: NPC Verwaltung
    permission: galacticfy.npc.manage

  npcreload:
    description: Lädt alle NPCs neu
    permission: galacticfy.npc.reload

  questadmin:
    description: Öffnet das Quest-Admin-GUI
    usage: /questadmin
    permission: galacticfy.quests.admin
    permission-message: §cDazu hast du keine Berechtigung.

  gamemode:
    description: Galacticfy Gamemode-System
    usage: /gamemode <mode> [spieler]
    aliases: [gm]
    permission: galacticfy.gamemode
    permission-message: §cDazu hast du keine Berechtigung.

  back:
    description: Teleportiert dich zu deinem letzten Ort (server-intern)
    usage: /back

  spawn:
    description: Teleportiert dich zum Server-Spawn
    usage: /spawn

  setspawn:
    description: Setzt den Server-Spawn auf deine Position
    usage: /setspawn
